---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loy
  labels:
    app: loy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: loy
  template:
    metadata:
      labels:
        app: loy
    spec:
      containers:
        - name: loy
          image: docker.io/phengbunath/loy:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
